version: "3.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=redmine"
  redmine:
    image: redmine:latest
    restart: always
    networks:
      - redmine
    ports:
      - 3000:3000
    volumes:
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/data:/usr/src/redmine/files
    environment:
      - "REDMINE_DB_POSTGRES=postgres"
      - "REDMINE_DB_DATABASE=redmine"
      - "REDMINE_DB_PASSWORD=password"
volumes:
  postgres-data:
  redmine-data:
networks:
  redmine:
    driver: bridge
